// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	dtos "jucabet/stori-challenge/process-transactions/internal/domain/dtos"

	mock "github.com/stretchr/testify/mock"
)

// IStorageRepository is an autogenerated mock type for the IStorageRepository type
type IStorageRepository struct {
	mock.Mock
}

// MoveFile provides a mock function with given fields: src, dest
func (_m *IStorageRepository) MoveFile(src *dtos.MoveFileDto, dest *dtos.MoveFileDto) error {
	ret := _m.Called(src, dest)

	var r0 error
	if rf, ok := ret.Get(0).(func(*dtos.MoveFileDto, *dtos.MoveFileDto) error); ok {
		r0 = rf(src, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIStorageRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewIStorageRepository creates a new instance of IStorageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIStorageRepository(t mockConstructorTestingTNewIStorageRepository) *IStorageRepository {
	mock := &IStorageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
