// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	dtos "jucabet/stori-challenge/send-reports/internal/domain/dtos"

	mock "github.com/stretchr/testify/mock"
)

// IMailerService is an autogenerated mock type for the IMailerService type
type IMailerService struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: _a0
func (_m *IMailerService) SendEmail(_a0 *dtos.SendEmailDto) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*dtos.SendEmailDto) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIMailerService interface {
	mock.TestingT
	Cleanup(func())
}

// NewIMailerService creates a new instance of IMailerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIMailerService(t mockConstructorTestingTNewIMailerService) *IMailerService {
	mock := &IMailerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
