// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ISecretInterface is an autogenerated mock type for the ISecretInterface type
type ISecretInterface struct {
	mock.Mock
}

// LoadSecrets provides a mock function with given fields:
func (_m *ISecretInterface) LoadSecrets() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewISecretInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewISecretInterface creates a new instance of ISecretInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewISecretInterface(t mockConstructorTestingTNewISecretInterface) *ISecretInterface {
	mock := &ISecretInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
